2 button component
Mens-Ludos/pearlydrive pull request #5
Opened 2022-07-16 15:43 UTC by kostyamospan

2022-07-18 18:46 UTC, gymnasy55 requested changes

2022-07-18 18:46 UTC, gymnasy55 commented on libs/landing-ui/src/lib/components/HollowButton/HollowButton.tsx
> +    color: theme.colors.primary.white,
You don't need to create a new component, you can use just `<Text color="primary.white">text</Text>`

2022-07-18 18:46 UTC, gymnasy55 commented on libs/landing-ui/src/lib/components/HollowButton/HollowButton.tsx
> +          width={props.width ?? '266px'}
You can set this value in destructuring

2022-07-18 18:46 UTC, gymnasy55 commented on libs/landing-ui/src/lib/components/HollowButton/HollowButton.tsx
> +          height={props.height ?? '96px'}
You can set this value in destructuring

2022-07-18 18:46 UTC, gymnasy55 commented on libs/landing-ui/src/lib/components/HollowButton/HollowButton.tsx
> +      <Box padding={'5px'}>
Please use tag button as button, not Box

2022-07-18 18:46 UTC, gymnasy55 commented on libs/landing-ui/src/lib/components/HollowButton/HollowButton.tsx
> +              {capital ? title.toUpperCase() : title}
Do not use title prop, use children and in css use condition in `text-transform`

2022-07-18 19:01 UTC, kostyamospan commented on libs/landing-ui/src/lib/components/HollowButton/HollowButton.tsx
> +          width={props.width ?? '266px'}
kak, tell me please

2022-07-18 19:37 UTC, gymnasy55 requested changes

2022-07-18 19:37 UTC, gymnasy55 commented on libs/landing-ui/src/lib/components/HollowButton/HollowButton.tsx
> +              {title}
no please remove title as a prop at all, use children instead

2022-07-19 13:18 UTC, gymnasy55 approved these changes

2022-07-19 13:18 UTC, merged